WebProgramlamaOdev/Controllers/BolumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebProgramlamaOdev.Models;

namespace WebProgramlamaOdev.Controllers
{
    public class BolumController : Controller
    {
        private BolumlerContext _context = new BolumlerContext();

        // GET: Bolum
        public async Task<IActionResult> Index()
        {
            if (HttpContext.Session.GetString("Sessionuseradm") is null)
            {
                return RedirectToAction("Index", "Home");
            }
            return _context.Bolumler != null ? 
                          View(await _context.Bolumler.ToListAsync()) :
                          Problem("Entity set 'BolumlerContext.Bolumler'  is null.");
        }

        // GET: Bolum/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (HttpContext.Session.GetString("Sessionuseradm") is null)
            {
                return RedirectToAction("Index", "Home");
            }
            if (id == null || _context.Bolumler == null)
            {
                return NotFound();
            }

            var bolum = await _context.Bolumler
                .FirstOrDefaultAsync(m => m.BolumID == id);
            if (bolum == null)
            {
                return NotFound();
            }

            return View(bolum);
        }

        // GET: Bolum/Creat
        public IActionResult Create()
        {
            if (HttpContext.Session.GetString("Sessionuseradm") is null)
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        // POST: Bolum/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Create([Bind("BolumID,BolumAdi")] Bolum bolum)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _context.Add(bolum);
        //        await _context.SaveChangesAsync();
        //        return RedirectToAction(nameof(Index));
        //    }
        //    return View(bolum);
        //}

        [HttpPost]
        public IActionResult Create (Bolum y)
        {
            if (HttpContext.Session.GetString("Sessionuseradm") is null)
            {
                return RedirectToAction("Index", "Home");
            }
            _context.Add(y);
                _context.SaveChanges();
                return RedirectToAction("Index");
            
        }

        // GET: Bolum/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (HttpContext.Session.GetString("Sessionuseradm") is null)
            {
                return RedirectToAction("Index", "Home");
            }
            if (id == null || _context.Bolumler == null)
            {
                return NotFound();
            }

            var bolum = await _context.Bolumler.FindAsync(id);
            if (bolum == null)
            {
                return NotFound();
            }
            return View(bolum);
        }

        // POST: Bolum/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BolumID,BolumAdi")] Bolum bolum)
        {
            if (HttpContext.Session.GetString("Sessionuseradm") is null)
            {
                return RedirectToAction("Index", "Home");
            }
            if (id != bolum.BolumID)
            {
                return NotFound();
            }

            
                    _context.Update(bolum);
                    await _context.SaveChangesAsync();
                
               
                return RedirectToAction(nameof(Index));
            
        }

        // GET: Bolum/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (HttpContext.Session.GetString("Sessionuseradm") is null)
            {
                return RedirectToAction("Index", "Home");
            }
            if (id == null || _context.Bolumler == null)
            {
                return NotFound();
            }

            var bolum = await _context.Bolumler
                .FirstOrDefaultAsync(m => m.BolumID == id);
            if (bolum == null)
            {
                return NotFound();
            }

            return View(bolum);
        }

        // POST: Bolum/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (HttpContext.Session.GetString("Sessionuseradm") is null)
            {
                return RedirectToAction("Index", "Home");
            }
            if (_context.Bolumler == null)
            {
                return Problem("Entity set 'BolumlerContext.Bolumler'  is null.");
            }
            var bolum = await _context.Bolumler.FindAsync(id);
            if (bolum != null)
            {
                _context.Bolumler.Remove(bolum);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BolumExists(int id)
        {
          return (_context.Bolumler?.Any(e => e.BolumID == id)).GetValueOrDefault();
        }
    }
}

WebProgramlamaOdev/Controllers/DoktorController.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebProgramlamaOdev.Models;

namespace WebProgramlamaOdev.Controllers
{
    public class DoktorController : Controller
    {
		private BolumlerContext _context = new BolumlerContext();

		// GET: Doktor
		public async Task<IActionResult> Index()
        {
            if (HttpContext.Session.GetString("Sessionuseradm") is null)
            {
                return RedirectToAction("Index", "Home");
            }

            var bolumlerContext = _context.Doktorlar.Include(d => d.Bolum);
                return View(await bolumlerContext.ToListAsync());
            
        }
   

        // GET: Doktor/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (HttpContext.Session.GetString("Sessionuseradm") is null)
            {
                return RedirectToAction("Index", "Home");
            }
            if (id == null || _context.Doktorlar == null)
            {
                return NotFound();
            }

            var doktor = await _context.Doktorlar
                .Include(d => d.Bolum)
                .FirstOrDefaultAsync(m => m.DoktorID == id);
            if (doktor == null)
            {
                return NotFound();
            }

            return View(doktor);
        }

        // GET: Doktor/Creat
        public IActionResult Create()
        {
            if (HttpContext.Session.GetString("Sessionuseradm") is null)
            {
                return RedirectToAction("Index", "Home");
            }
            ViewData["BolumID"] = new SelectList(_context.Bolumler, "BolumID", "BolumAdi");
            return View();
        }

        // POST: Doktor/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DoktorID,DoktorAdi,DoktorSoyadi,BolumID")] Doktor doktor)
        {
            if (HttpContext.Session.GetString("Sessionuseradm") is null)
            {
                return RedirectToAction("Index", "Home");
            }

            _context.Add(doktor);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index)); 
        }

        // GET: Doktor/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (HttpContext.Session.GetString("Sessionuseradm") is null)
            {
                return RedirectToAction("Index", "Home");
            }
            if (id == null || _context.Doktorlar == null)
            {
                return NotFound();
            }

            var doktor = await _context.Doktorlar.FindAsync(id);
            if (doktor == null)
            {
                return NotFound();
            }
            ViewData["BolumID"] = new SelectList(_context.Bolumler, "BolumID", "BolumAdi", doktor.BolumID);
            return View(doktor);
        }

        // POST: Doktor/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("DoktorID,DoktorAdi,DoktorSoyadi,BolumID")] Doktor doktor)
        {
            if (id != doktor.DoktorID)
            {
                return NotFound();
            }

           
                    _context.Update(doktor);
                    await _context.SaveChangesAsync();
                
                
                
                return RedirectToAction(nameof(Index));
            
        }

        // GET: Doktor/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Doktorlar == null)
            {
                return NotFound();
            }

            var doktor = await _context.Doktorlar
                .Include(d => d.Bolum)
                .FirstOrDefaultAsync(m => m.DoktorID == id);
            if (doktor == null)
            {
                return NotFound();
            }

            return View(doktor);
        }

        // POST: Doktor/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Doktorlar == null)
            {
                return Problem("Entity set 'BolumlerContext.Doktorlar'  is null.");
            }
            var doktor = await _context.Doktorlar.FindAsync(id);
            if (doktor != null)
            {
                _context.Doktorlar.Remove(doktor);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DoktorExists(int id)
        {
          return (_context.Doktorlar?.Any(e => e.DoktorID == id)).GetValueOrDefault();
        }
    }
}

WebProgramlamaOdev/Controllers/HastaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebProgramlamaOdev.Models;

namespace WebProgramlamaOdev.Controllers
{
    public class HastaController : Controller
    {
        private BolumlerContext _context = new BolumlerContext();

        // GET: Hasta
        public async Task<IActionResult> Index()
        {
            if (HttpContext.Session.GetString("Sessionuseradm") is null)
            {
                return RedirectToAction("Index", "Home");
            }
            return _context.Hastalar != null ? 
                          View(await _context.Hastalar.ToListAsync()) :
                          Problem("Entity set 'BolumlerContext.Hastalar'  is null.");
        }

        // GET: Hasta/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Hastalar == null)
            {
                return NotFound();
            }

            var hasta = await _context.Hastalar
                .FirstOrDefaultAsync(m => m.HastaID == id);
            if (hasta == null)
            {
                return NotFound();
            }

            return View(hasta);
        }

        // GET: Hasta/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Hasta/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("HastaID,HastaAdSoyad,HastaTC,HastaPass")] Hasta hasta)
        {
           
                _context.Add(hasta);
                await _context.SaveChangesAsync();
                

            return RedirectToAction("HastaGiris", "Home");
        }

        // GET: Hasta/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (HttpContext.Session.GetString("Sessionuseradm") is null)
            {
                return RedirectToAction("Index", "Home");
            }
            if (id == null || _context.Hastalar == null)
            {
                return NotFound();
            }

            var hasta = await _context.Hastalar.FindAsync(id);
            if (hasta == null)
            {
                return NotFound();
            }
            return View(hasta);
        }

        // POST: Hasta/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("HastaID,HastaTC,HastaPass")] Hasta hasta)
        {
            if (HttpContext.Session.GetString("Sessionuseradm") is null)
            {
                return RedirectToAction("Index", "Home");
            }
            if (id != hasta.HastaID)
            {
                return NotFound();
            }

            
                    _context.Update(hasta);
                    await _context.SaveChangesAsync();
               
                   
                return RedirectToAction(nameof(Index));
           
        }

        // GET: Hasta/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (HttpContext.Session.GetString("Sessionuseradm") is null)
            {
                return RedirectToAction("Index", "Home");
            }
            if (id == null || _context.Hastalar == null)
            {
                return NotFound();
            }

            var hasta = await _context.Hastalar
                .FirstOrDefaultAsync(m => m.HastaID == id);
            if (hasta == null)
            {
                return NotFound();
            }

            return View(hasta);
        }

        // POST: Hasta/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (HttpContext.Session.GetString("Sessionuseradm") is null)
            {
                return RedirectToAction("Index", "Home");
            }
            if (_context.Hastalar == null)
            {
                return Problem("Entity set 'BolumlerContext.Hastalar'  is null.");
            }
            var hasta = await _context.Hastalar.FindAsync(id);
            if (hasta != null)
            {
                _context.Hastalar.Remove(hasta);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HastaExists(int id)
        {
          return (_context.Hastalar?.Any(e => e.HastaID == id)).GetValueOrDefault();
        }
    }
}

WebProgramlamaOdev/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebProgramlamaOdev</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebProgramlamaOdev.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebProgramlamaOdev</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Bolum" asp-action="Index">Bolumler</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Doktor" asp-action="Index">Doktorlar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CalismaSaati" asp-action="Index">Saatler</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Hasta" asp-action="Index">Hasta İşlemleri</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Randevu" asp-action="Index">Randevu İşlemleri</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Cikis">Çıkış</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebProgramlamaOdev - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebProgramlamaOdev/Views/Shared/_LayoutAna.cshtml
<style>
    body {
        background-image: url('/resimler/arkaplan.jpg');
        background-size: cover;
        background-position: center;
        /* İsterseniz ekstra stiller ekleyebilirsiniz */
    }

    footer {
        position: fixed;
        bottom: 0;
        width: 100%;
        background-color: #f8f9fa; /* İsterseniz arka plan rengini ayarlayabilirsiniz */
        padding: 10px 0; /* İsteğe bağlı: footer içeriğine boşluk ekler */
        .col-md-4

    {
        width: 200px;
        max-width: 100%;
    }

    .row {
        /* border-radius: 5px;
            background-color: rgba(13, 202, 240, 0.52);*/
        display: flex;
        margin-left: 150px;
        align-content: center;
        justify-content: center;
        width: 400px;
    }

    h4 {
        /* background-color: rgba(13, 202, 240, 0.52); /* Rengi ve saydamlığı buradan ayarlayabilirsin
              border-radius: 5px; */ /* İsteğe bağlı: Köşeleri yuvarlama */
        padding: 10px;
        margin-right: 145px;
        margin-left: 150px;
        max-width: 400px; /* veya istediğin genişlik */
        width: 100%;
    }

    .pb-3 {
        height: 73vh;
    }

    .btn-primary {
        color: #fff;
        background-color: #1c0df0b3; /* Bu kısım butonun arka plan rengini belirler */
        border-color: #1c0df0b3; /* Bu kısım butonun kenarlık rengini belirler */
    }

    .center-container {
        display: flex;
        align-items: center;
        justify-content: center;
        height: 100vh;
        background-image: url('/resimler/arkaplan.jpg'); /* Resim yolunu doğru şekilde güncelleyin */
        background-size: cover; /* Resmi kaplamak için */
        background-position: center;
    }

    .form-container {
        max-width: 400px; /* veya istediğin genişlik */
        width: 100%;
    }
    }
</style>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebProgramlamaOdev</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebProgramlamaOdev.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebProgramlamaOdev</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">@_localization.Getkey("layAnaSayfa")</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="HastaGiris">@_localization.Getkey("layRandevu")</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="RandevuControl">@_localization.Getkey("layRanGor")</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Giris">@_localization.Getkey("layAdmin")</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark">@Context.Session.GetString("Sessionuser")</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Cikis">@_localization.Getkey("layCikis")</a>
                        </li>
                        <li>
                           <div class="dropdown">
                               <button type="button"class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown">Localization</button>
                               <ul class="dropdown-menu">
                                   <li>
                                       <a asp-controller="Home" asp-action="ChangeLanguage" asp-route-culture="tr-TR"
                                       class="dropdown-item">
                                       <i class="flag-icon flag-icon-gb"></i>Türkçe</a> 
                                   </li>
                                    <li>
                                        <a asp-controller="Home" asp-action="ChangeLanguage" asp-route-culture="en-US"
                                           class="dropdown-item">
                                            <i class="flag-icon flag-icon-gb"></i>İngilizce
                                        </a>
                                    </li>
                               </ul>
                           </div>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebProgramlamaOdev - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>